version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install dependencies needed for running tests
      - echo Installing source NPM dependencies...
      - npm install
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - reports/**/*